Feature/darkmode
charludo/ycms pull request #101
Opened 2023-12-26 00:19 UTC by noworneverev

### Short description
Add dark mode

### Proposed changes

### Side effects

### Resolved issues

Fixes: #58

2023-12-26 13:32 UTC, charludo requested changes
Wow, really nice! Love the dark mode look, will definitely be using this from now on :D 

A couple theme-related things I noticed:
- the yellow buttons are a bit too bright for dark mode IMO. Could you maybe change them to something like `dark:bg-gray-800 dark:text-primary dark:hover:bg-primary dark:hover:text-gray-800`? (I think you can just apply those as-is in the scss file)
- the red "x" marks for privately insured/accompanied are really hard to read in the patient cards, maybe a lighter red would be easier?
- the theme switcher button sitze really awkwardly - maybe that's just in my browser though? Could you move it (plus maybe "Toggle theme" or something like that) above or below the timetravel button? 
![grafik](https://github.com/charludo/ycms/assets/47758554/9850d66a-bcde-448b-8ce5-5fac13dfd009)

The login screen is always in bright mode, which I guess is a consequence of the way the theme is toggled (really interesting btw, I would probably just have just have set something in localStorage, but this is undoubtedly nicer).

2023-12-28 10:38 UTC, noworneverev commented
> Wow, really nice! Love the dark mode look, will definitely be using this from now on :D
> 
> A couple theme-related things I noticed:
> 
> * the yellow buttons are a bit too bright for dark mode IMO. Could you maybe change them to something like `dark:bg-gray-800 dark:text-primary dark:hover:bg-primary dark:hover:text-gray-800`? (I think you can just apply those as-is in the scss file)
ok
> * the red "x" marks for privately insured/accompanied are really hard to read in the patient cards, maybe a lighter red would be easier?
ok

> * the theme switcher button sitze really awkwardly - maybe that's just in my browser though? Could you move it (plus maybe "Toggle theme" or something like that) above or below the timetravel button?
Yeah, I move it below the timetravel button now.

>   ![grafik](https://private-user-images.githubusercontent.com/47758554/292874575-9850d66a-bcde-448b-8ce5-5fac13dfd009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTgyMjIsIm5iZiI6MTcwMzc1NzkyMiwicGF0aCI6Ii80Nzc1ODU1NC8yOTI4NzQ1NzUtOTg1MGQ2NmEtYmNkZS00NDhiLThjZTUtNWZhYzEzZGZkMDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDEwMDUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyZTgxZmYxZTk1Y2VjYmE5OWZlYmUwYTlmMjI0OGJjZDUwOTUyOWI5ZDg5NzQ4M2ZmNTZkNzE1OGU3NzM5MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ft0qJgeprY-7c5X5qsaf0JepDPNDSYRaY85JU2VNs3k)
> 
> The login screen is always in bright mode, which I guess is a consequence of the way the theme is toggled (really interesting btw, I would probably just have just have set something in localStorage, but this is undoubtedly nicer).
In the beginning, I used localStorage to store the state of the dark mode, as this is usually how other frontend frameworks deal with dark/light mode. However, when I tried using localStorage, every time I switched between pages, the page would flicker back to light mode and then to dark mode(potentially attributable to how Django renders different templates). Consequently, I had to find another way to implement the dark mode.

2023-12-28 12:43 UTC, charludo requested changes
Nice, thanks for the changes! I noticed another couple of small issues, see below.

Re: the local storage: oof, yeah, I can see how that would be annoying. IMO you found a REALLY nice solution.

2023-12-28 12:43 UTC, charludo commented on ycms/static/src/css/style.scss
> +        @apply font-bold rounded inline-block bg-primary text-gray-700 py-3 px-4 border-2 border-primary dark:bg-gray-800 dark:text-primary dark:hover:bg-primary dark:hover:text-gray-800;
```suggestion
        @apply font-bold rounded inline-block bg-primary text-gray-700 py-3 px-4 border-2 border-primary dark:bg-gray-800 dark:text-primary;
```

My bad - `dark:hover:bg-primary dark:hover:text-gray-800` needs to go in the `&:hover{}` section a couple of line below, otherwise these styles are being overwritten.

2023-12-28 12:43 UTC, charludo commented on ycms/static/src/css/style.scss
> +    @apply text-gray-700 dark:text-gray-200;
Just noticed this overwrites the styles of the messages (after saving etc), both in light and in dark mode. You will have to move `text-blue-500` (and so on) from the `div` to the `p` within it in the messages section in `_raw.html`

2023-12-28 12:43 UTC, charludo commented on ycms/cms/templates/_base.html
> +    <div class="lg:flex dark:bg-gray-900">
```suggestion
    <div class="lg:flex dark:bg-gray-900 min-h-full">
```
Currently, if the content isn't taking up the full page, the white background is showing

2023-12-28 12:43 UTC, charludo commented on ycms/cms/templates/_base.html
> +                class="text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-600 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-800 rounded-lg text-sm p-2.5"
```suggestion
                class="text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-600 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-800 rounded-lg text-sm p-2.5 mb-4">
```
Optional.

Also optional, but maybe adding "Switch Theme" or something like that could make it clearer to users? I mean, we know what the button does, but not everyone might.

2023-12-28 16:38 UTC, noworneverev commented on ycms/cms/templates/_base.html
> +                class="text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-600 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-800 rounded-lg text-sm p-2.5"
I add a tooltip to display its purpose when users hover over it.

2023-12-29 08:47 UTC, charludo commented
Awesome! This is ready to merge, just please squash commits beforehand :)

2023-12-31 07:45 UTC, charludo approved these changes
Sry I missed the mail about the push

2023-12-31 12:52 UTC, merged