add loader
charludo/ycms pull request #105
Opened 2024-01-03 01:21 UTC by noworneverev

### Short description
add loader for page navigation and refreshing the page.

### Proposed changes
add loading effect for changing pages and time-consuming operation, for example, add patients, add wards, and assign patients, etc.
- 
- 

### Side effects

- 
- 

### Resolved issues

Fixes: #104

2024-01-03 08:05 UTC, charludo requested changes
In principal I like this idea, but I think there's an easier way.

```js
window.addEventListener("beforeunload", () => {
    showLoader();
});
```

This is all you need. However, I think we could make it even nicer by only showing the spinner after a short delay:

```js
window.addEventListener("beforeunload", () => {
    const TIMEOUT = 200;
    setTimeout(showLoader, TIMEOUT);
});
```

In my testing, values as low as `100` worked so that for normal page loads, the spinner was never shown, but for heavy ones (like the patient list) it still looks to the user as if the spinner is shown instantly.

You can even change the theme switch button to be a normal `a` element with a `href` to your theme switcher view, and this will also show the spinner for that!

One other thing, the spinner is a bit hard to see, could you give it a nice background?

2024-01-03 08:38 UTC, charludo commented
Also, I just noticed that I missed this in the dark mode review:

Is there a reason to create the spinner "by hand" in JS instead of just having it as a hidden element in the `_raw.html` file? It looks like that would be way easier

2024-01-03 17:18 UTC, noworneverev commented
> Also, I just noticed that I missed this in the dark mode review:
> 
> Is there a reason to create the spinner "by hand" in JS instead of just having it as a hidden element in the `_raw.html` file? It looks like that would be way easier

Good point, I move it to `_raw.html`.

2024-01-03 17:18 UTC, noworneverev commented
> In principal I like this idea, but I think there's an easier way.
> 
> ```js
> window.addEventListener("beforeunload", () => {
>     showLoader();
> });
> ```
> 
> This is all you need. However, I think we could make it even nicer by only showing the spinner after a short delay:
> 
> ```js
> window.addEventListener("beforeunload", () => {
>     const TIMEOUT = 200;
>     setTimeout(showLoader, TIMEOUT);
> });
> ```
> 
> In my testing, values as low as `100` worked so that for normal page loads, the spinner was never shown, but for heavy ones (like the patient list) it still looks to the user as if the spinner is shown instantly.
> 
> You can even change the theme switch button to be a normal `a` element with a `href` to your theme switcher view, and this will also show the spinner for that!
> 
> One other thing, the spinner is a bit hard to see, could you give it a nice background?

Done

2024-01-04 06:50 UTC, charludo requested changes
Please don't be mad... But I think we can simplify even further 😄 

BTW, the tests are failing with the divide by zero error because we are now in the time period of the test data Tabea originally gave us, and apparently the data includes bed assignments that trigger that bug.

Just do `git rebase origin/develop` to fix it, there's no merge conflicts.

2024-01-04 06:50 UTC, charludo commented on ycms/cms/templates/_base.html
> +        </a>
I've been meaning to ask, because I've seen you use the `button`-inside-`a` pattern a couple of times now, is there a reason to not just do this? 😄 
```suggestion
        <a href="{% url 'change-theme' %}"
              data-tooltip-target="tooltip-right"
              data-tooltip-placement="right"
              class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-600 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-800 rounded-lg text-sm p-2.5 mb-4">
          {% if is_dark_theme %}
              <i icon-name="sun"></i>
          {% else %}
              <i icon-name="moon"></i>
          {% endif %}
        </a>
```

2024-01-04 06:50 UTC, charludo commented on ycms/cms/templates/_raw.html
>                              <p class="text-blue-500">{{ msg.message }}</p>
Hm... It is definitely more readable now, but I kinda miss the colored backgrounds :(

Making the text color important works to override the `p` styling:
```suggestion
                        <div class="message bg-blue-100 border-l-4 border-blue-500 dark:bg-gray-700 dark:border-blue-400"
                             role="alert">
                            <p class="!text-blue-500">{{ msg.message }}</p>
```
Or do you think the green backgrounds are too bright for dark mode?

2024-01-04 06:50 UTC, charludo commented on ycms/cms/templates/bed_assignment/assign_bed_assignment.html
> +                            <a href="{{ url }}">
I think this can be undone du to the new JS, right?
```suggestion
                            <a href="{% url 'cms:protected:ward_detail' pk=ward.id %}">
```

2024-01-04 06:50 UTC, charludo commented on ycms/cms/templates/patient/patient_card.html
> +                        <a href="{{ url }}">
Same here - do correct me if I'm wrong though!!
```suggestion
                        <a href="{% url 'cms:protected:assign_patient' ward_id=ward.id assignment_id=bed_assignment.id %}">
```

2024-01-04 06:50 UTC, charludo commented on ycms/cms/templates/patients_list.html
> +                                              class="update-patient-form"
```suggestion
```
As far as I can tell, this is the only place this class is mentioned in the code

2024-01-04 06:50 UTC, charludo commented on ycms/cms/templates/ward/ward_info.html
> +                                id="ward-option-{{ ward.id }}"
Unsure what has happened here - was there a bug caused by this previously?

2024-01-04 06:50 UTC, charludo commented on ycms/static/src/css/style.scss
> +}
OK, this is all definitiely correct, but why not just use the corresponding tailwind classes? 😅

2024-01-04 06:50 UTC, charludo commented on ycms/cms/templates/_raw.html
> +        </div>
This is the loader with the tailwind classes (meaning you can completely remove the scss changes):
```suggestion
        <div id="loader-container" class="hidden relative">
            <div class="fixed top-0 left-0 right-0 bottom-0 bg-black/50 z-[9998]"></div>
            <div class="text-blue-800 dark:text-blue-600 fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-[9999]">
                <i icon-name="loader-2" class="w-12 h-12 animate-spin"></i>
            </div>
        </div>
```
(Feel free to change the colors. Also, the lucide spinner is not multi-colorable, so if you want that, feel free to keep the svg; I just thought it was a bit cleaner like this)

2024-01-04 06:50 UTC, charludo commented on ycms/static/src/js/utils/loader.ts
>  };
```suggestion
```
Unless I am missing something, this is not necessary, since the loader already loads with the class `hidden`

2024-01-04 06:50 UTC, charludo commented on ycms/static/src/js/utils/loader.ts
> +});
```suggestion
    hideLoader();
});
```
And then this is no longer required, too (sorry, can't mark the first line on github for some reason)

2024-01-04 23:24 UTC, noworneverev commented on ycms/cms/templates/_raw.html
>                              <p class="text-blue-500">{{ msg.message }}</p>
Both are fine for me, I'm not sensible to colors😅 I change the backgrounds to their respective darker ones in dark mode.

2024-01-04 23:34 UTC, noworneverev commented on ycms/cms/templates/ward/ward_info.html
> +                                id="ward-option-{{ ward.id }}"
Well, no, just trying to give it a meaningful id😅

2024-01-05 06:07 UTC, charludo commented on ycms/cms/templates/_raw.html
>                              <p class="text-blue-500">{{ msg.message }}</p>
Alright, looks great now!!

2024-01-05 06:08 UTC, charludo commented on ycms/cms/templates/ward/ward_info.html
> +                                id="ward-option-{{ ward.id }}"
OK 😄

2024-01-05 06:11 UTC, charludo requested changes
Alright! 🎉 

Just the bit of now-superfluous css, squash the commits, and then it's ready to merge :)

2024-01-05 06:11 UTC, charludo commented on ycms/static/src/css/style.scss
> +}
```suggestion
```

2024-01-05 18:18 UTC, charludo approved these changes
🎉

2024-01-05 19:19 UTC, merged