Feature/responsive design
charludo/ycms pull request #127
Opened 2024-01-13 20:59 UTC by noworneverev

### Short description

Improve the responsiveness of the website

### Proposed changes

- fix sidebar, add backdrop when open sidebar in small screen
- patient card's buttons in small screen
- font size in patient data(font size was too large in small screen)
- create user in small screen
- time travel control in small screen

### Side effects

- 
- 

### Resolved issues

Fixes: #125

2024-01-14 08:01 UTC, charludo commented
Awesome, thank you so much for tackling this issue.

Really, really nice progress already. I noticed a couple of additional things:
- ward view: the ward selection header is overflowing. Maybe the timeline toggle can just be placed an a second line?
- ward view sidebar: clicking "discharge" seems to bring up the confirmation modal (background overlay is shown), but somewhere out of frame
- the success/error notifications cling to the left side of the screen
- timeline view: same thing as ward view header, plus when a change was made, it overflows even further
- the timeline seems to have a higher z-index than the mobile menu (it's visible over the menu)
- ward management: the form should probably just not be shown as flex anymore on mobile, same with the "at a glance" section; not sure what to do with the table though
- same thing with the patient list table. I just tried it out, you *could* give each `tr` and `td` element a class like `block` on small screens, then the table structure is at least broken
- the same changes you made to the login form probably should also be made to the password reset request and password request confirm templates

> overlap when opening sidebar in patient intake, already know that if removing all position: relative can solve the issue, including tom-select's position: relative (don't know how to remove this one)
As far as I can tell, it's enough to set a higher z-index on both the `#sidebar` and `#sidebarBackdrop`. They are currently set to `z-100`, try `z-[999]` and `z-[998]`, respectively. This also fixes the issue for the timeline!

2024-01-14 17:50 UTC, noworneverev commented
@charludo Not sure why the test fails after rebasing the latest develop branch. It can be solved by adding checks to cached property. Should I modify this?

```python
    @cached_property
    def current_admission_date(self):
        """
        Helper property for accessing the patient's current admission date

        :return: the current admission date
        :rtype: str
        """
        if not self.current_stay:
            return None
        return self._get_date_status(self.current_stay.admission_date)

    @cached_property
    def current_discharge_date(self):
        """
        Helper property for accessing the patient's current discharge date

        :return: the current discharge date
        :rtype: str
        """
        if not self.current_stay:
            return None
        return self._get_date_status(self.current_stay.discharge_date)
```

2024-01-15 05:41 UTC, charludo commented
> @charludo Not sure why the test fails after rebasing the latest develop branch. It can be solved by adding checks to cached property. Should I modify this?
> 
> ```python
>     @cached_property
>     def current_admission_date(self):
>         """
>         Helper property for accessing the patient's current admission date
> 
>         :return: the current admission date
>         :rtype: str
>         """
>         if not self.current_stay:
>             return None
>         return self._get_date_status(self.current_stay.admission_date)
> 
>     @cached_property
>     def current_discharge_date(self):
>         """
>         Helper property for accessing the patient's current discharge date
> 
>         :return: the current discharge date
>         :rtype: str
>         """
>         if not self.current_stay:
>             return None
>         return self._get_date_status(self.current_stay.discharge_date)
> ```

Hey, sorry for not seeing this earlier. Apologies, this is my fault. I forgot to add a test patient which we could use for tests indefinitely. One of the patients That were used in the tests must have been discharged yesterday evening.

I have [added this test case here](https://github.com/charludo/ycms/pull/120/commits/e0baac5c2114b3ec8ddad9c02ac3bd8a050a706f). It's a single patient which will stay in the hospital for another 5 years... 😄 That should hopefully do it ^^

The first thing `_get_date_status()` does is check if the passed date is `None`, so in actual usecases we are already safe. IDK if the additional checks are necessary, since this time, they did uncover an actual error. Then again, they don't hurt either, so... Your choice if you want to keep them in.

2024-01-15 05:59 UTC, charludo requested changes
Nice! Again, thank you so much for doing this issue.

I have a couple small requests:

- the ward/timeline switch is much better now, except it's not aligned with the "Ward" title above it. That one has a x-padding of 4, maybe we could remove that on small screens?
- when assigning/transfering a patient, could you break up the "More reassignment options" and the drop down? Just setting `md:flex` or `lg:flex` instead of just `flex` does the trick. And then the "Unassign" button below it should also lose its left padding on small screens
- the success/error notifications still cling to the left of the screen. Setting the top and right values to `md:top-8 md:right-8` on `#messages` in `_raw.html` does the trick.
- the number of unsaved bed assignments in the ward view is still unreadable on mobile. Setting `flex-wrap` on `#change-counter` and wrapping the span and the "unsaved bed assignment changes" in a div works, I think. Alternatively, if you find a way to also make the 2 buttons take the full width together, that would look ieven nicer, but not necessary
- the header of the patient list can probably just be hidden on mobile
- I get what you did with the table, but it's really necessary that we are still able to access the details from there 😅 I get that this table is a fair bit of work though, if you think it's out of scope for this PR, feel free to instead create a new issue.

2024-01-15 18:54 UTC, charludo commented on ycms/cms/templates/timetravel_controls.html
> +    </div>
```suggestion
    <button class="hidden md:!inline-block btn btn-outline-plain"
            data-minutes="-1440">
        <i icon-name="chevrons-left"></i>{% translate "day" %}
    </button>
    <button class="hidden md:!inline-block btn btn-outline-plain"
            data-minutes="-60">
        <i icon-name="chevrons-left"></i>{% translate "hour" %}
    </button>
    <button class="hidden md:!inline-block btn btn-outline-plain"
            data-minutes="-1">
        <i icon-name="chevrons-left"></i>{% translate "minute" %}
    </button>
    {# djlint:off #}
    <input type="datetime-local" style="width: auto !important; box-shadow: none !important;" />
    {# djlint:on #}
    <button class="hidden md:!inline-block btn btn-outline-plain"
            data-minutes="1">
        {% translate "minute" %}<i icon-name="chevrons-right"></i>
    </button>
    <button class="hidden md:!inline-block btn btn-outline-plain"
            data-minutes="60">
        {% translate "hour" %}<i icon-name="chevrons-right"></i>
    </button>
    <button class="hidden md:!inline-block btn btn-outline-plain"
            data-minutes="1440">
        {% translate "day" %}<i icon-name="chevrons-right"></i>
    </button>
```

What do you think about this? The controls take up quite a lot of screen space on mobile, and since the datepicker is technically enough to set everything and the buttons are just for convenience, I thought this might work, too?

2024-01-15 19:20 UTC, noworneverev commented on ycms/cms/templates/timetravel_controls.html
> +    </div>
Looks good, but I just noticed that when I choose a specific time, after clicking outside to apply the change, the time displayed on the control decreases by one hour. This is the bug right?

2024-01-15 19:53 UTC, charludo commented on ycms/cms/templates/timetravel_controls.html
> +    </div>
That might be related to the change in timezone in #114...

I'm currently working on a PR to fix a bunch of bugs with the time travelling, guess I'll add it to the list 😅

Thanks for noticing and pointing it out!

2024-01-15 21:04 UTC, noworneverev commented
> Nice! Again, thank you so much for doing this issue.
> 
> I have a couple small requests:
> 
> * the ward/timeline switch is much better now, except it's not aligned with the "Ward" title above it. That one has a x-padding of 4, maybe we could remove that on small screens?

Do You mean `space-x-4` in `ward_selection_form.html`? If so, I think this one is necessary, otherwise the select element is too close to the word "Ward".

> * when assigning/transfering a patient, could you break up the "More reassignment options" and the drop down? Just setting `md:flex` or `lg:flex` instead of just `flex` does the trick. And then the "Unassign" button below it should also lose its left padding on small screens

ok

> * the success/error notifications still cling to the left of the screen. Setting the top and right values to `md:top-8 md:right-8` on `#messages` in `_raw.html` does the trick.

But I already set top and right like follows, I did't see any different after I add  `md:top-8 md:right-8`.

```html
            <div id="messages"
                 class="absolute top-8 right-8 flex flex-col max-w-screen-sm z-50">
```

> * the number of unsaved bed assignments in the ward view is still unreadable on mobile. Setting `flex-wrap` on `#change-counter` and wrapping the span and the "unsaved bed assignment changes" in a div works, I think. Alternatively, if you find a way to also make the 2 buttons take the full width together, that would look ieven nicer, but not necessary

ok

> * the header of the patient list can probably just be hidden on mobile

I think it's needed, no reason to show different context in different screen size, except the layout.

> * I get what you did with the table, but it's really necessary that we are still able to access the details from there 😅 I get that this table is a fair bit of work though, if you think it's out of scope for this PR, feel free to instead create a new issue.

It's tricky to make the table responsive. This is the best I can do for now, but I just noticed that on a small screen, the fields, except for the name field, will not be shown since I intentionally hid them.

2024-01-16 06:30 UTC, charludo commented
> Do You mean `space-x-4` in `ward_selection_form.html`? If so, I think this one is necessary, otherwise the select element is too close to the word "Ward".

No, in `ward_selection_form`, replace `p-4` with `md:px-4 py-4` (right next to `space-x-4`).

Without: 
![image](https://github.com/charludo/ycms/assets/47758554/ecd56a59-bba2-4436-b9e0-f41ded7f4a0d)
With: 
![image](https://github.com/charludo/ycms/assets/47758554/4c854f51-3988-47b2-8c8c-2881349620ca)

2024-01-16 06:33 UTC, charludo commented on ycms/cms/templates/_raw.html
> +                 class="absolute top-8 right-8 flex flex-col max-w-screen-sm z-50">
> But I already set top and right like follows, I did't see any different after I add `md:top-8 md:right-8`.
> 
> ```
>             <div id="messages"
>                  class="absolute top-8 right-8 flex flex-col max-w-screen-sm z-50">
> ```

```suggestion
                 class="absolute md:top-8 md:right-8 flex flex-col max-w-screen-sm z-50">
```

Without: 
![image](https://github.com/charludo/ycms/assets/47758554/b1e0709c-422c-4844-b175-c3a0061e6053)

With:
![image](https://github.com/charludo/ycms/assets/47758554/7df12784-6386-42b9-9399-d4292bbb933f)

2024-01-16 06:38 UTC, charludo commented on ycms/cms/templates/timeline/timeline.html
> +                    <div class="flex flex-row gap-2 w-full">
```suggestion
                    <div class="shrink-0">
```
No difference on mobile, but on Desktop:

Without: 
![image](https://github.com/charludo/ycms/assets/47758554/20352085-a555-4e84-b46f-f2fb588dc09f)

With: 
![image](https://github.com/charludo/ycms/assets/47758554/25a6e8cd-a77a-4872-8a55-2c4c4e65316e)

2024-01-16 06:40 UTC, charludo commented
> But I already set top and right like follows, I did't see any different after I add `md:top-8 md:right-8`.
> 
> ```
>             <div id="messages"
>                  class="absolute top-8 right-8 flex flex-col max-w-screen-sm z-50">
> ```



> > Nice! Again, thank you so much for doing this issue.
> > I have a couple small requests:
> > 
> > * the ward/timeline switch is much better now, except it's not aligned with the "Ward" title above it. That one has a x-padding of 4, maybe we could remove that on small screens?
> 
> Do You mean `space-x-4` in `ward_selection_form.html`? If so, I think this one is necessary, otherwise the select element is too close to the word "Ward".
> 
> > * when assigning/transfering a patient, could you break up the "More reassignment options" and the drop down? Just setting `md:flex` or `lg:flex` instead of just `flex` does the trick. And then the "Unassign" button below it should also lose its left padding on small screens
> 
> ok
> 
> > * the success/error notifications still cling to the left of the screen. Setting the top and right values to `md:top-8 md:right-8` on `#messages` in `_raw.html` does the trick.
> 
> But I already set top and right like follows, I did't see any different after I add `md:top-8 md:right-8`.
> 
> ```
>             <div id="messages"
>                  class="absolute top-8 right-8 flex flex-col max-w-screen-sm z-50">
> ```
> 
> > * the number of unsaved bed assignments in the ward view is still unreadable on mobile. Setting `flex-wrap` on `#change-counter` and wrapping the span and the "unsaved bed assignment changes" in a div works, I think. Alternatively, if you find a way to also make the 2 buttons take the full width together, that would look ieven nicer, but not necessary
> 
> ok
> 
> > * the header of the patient list can probably just be hidden on mobile
> 
> I think it's needed, no reason to show different context in different screen size, except the layout.
> 
> > * I get what you did with the table, but it's really necessary that we are still able to access the details from there 😅 I get that this table is a fair bit of work though, if you think it's out of scope for this PR, feel free to instead create a new issue.
> 
> It's tricky to make the table responsive. This is the best I can do for now, but I just noticed that on a small screen, the fields, except for the name field, can not be edited since I intentionally hid them.

Alright, then please open a new issue for that.

2024-01-16 11:30 UTC, charludo commented
Nice! Please squash the commits, and then it's ready to merge.

2024-01-16 12:00 UTC, charludo approved these changes

2024-01-16 12:04 UTC, merged