Feature/bed assignment management
charludo/ycms pull request #55
Opened 2023-11-14 23:35 UTC by noworneverev

### Short description
Add Feature/bed assignment management

### Proposed changes

-  In ward view, users can edit the assignment and add a new assignment
-  Add another url [localhost/bed-assignments/](http://localhost:8086/bed-assignments/) to view and edit all bed assignments

### Side effects

- 
- 

### Resolved issues

Fixes: #49

2023-11-15 06:01 UTC, charludo requested changes
Thank you! I have not had a closer look at the code yet, just tried it out locally, and everything seems to work!

However, I have some concerns about the workflow, especially the BedAssignmentForm.

After clicking on "Assign" in the sidebar, the form pops up and we can manually set a bed. But all the other fields are irrelevant to the situation, and it is not intuitive at all what bed we are assigning to, plus we don't know if there is someone of a different gender, or much older/younger, or privately insured in the room.

Could you rework this so no form is shown at all? The new workflow would be: 

- Click "assign" in the sidebar
- The sidebar closes, and the user can click on any of the rooms
- The patient is assigned to the first free bed in the room (e.g. use JS to submit the form in the background)
- The sidebar reopens

Additionally, we would need to indicate that we are currently in the "assignment mode":

- show something like "Assigning patient {{ patient name,... }}" somewhere
- in place of the "Unassigned Patients: x" + buttons show the patients relevant information (age, gender, diagnosis)
- visually indicate what rooms they are assignable to: set background and text color of private, other-gender, and large age difference rooms to grey, make full rooms or rooms with one person if the patient is accompanied unselectable. 
- same thing when editing an assignment, but also indicate the current room

I really like the indications (large age gap, insurance state and so on) but I think they, too, should only be shown during assignment - afterwards, they don't really matter.

2023-11-15 06:10 UTC, charludo commented
Also some other "nitpicks":

- Why not put the assignment information and action in the free space we already have, in the same style? 
![image](https://github.com/charludo/ycms/assets/47758554/4f5fe4c2-6180-448d-a3d4-a192f7ab5bb0)
- "New Bed Assignment" is not necessary, unless I am missing a usecase?
- I like the new sidebar! Could you also show the same diagnosis information in the room sidebar?
- Maybe we could also show indurance type in the assignment sidebar?
- Don't show discharge date in the assignment. In fact, I think we can also remove discharge date ffrom the room sidebar: Realistically, either you are already discharged (and no longer show up in the room sidebar), or you don't have a discharge date. I know we have the discharge date in the data, but AFAIK that is only because we get the complete dataset all at once, rather than linearly in time.

I know these are a LOT of change requests, I'm sorry 🙈

2023-11-15 09:15 UTC, charludo reviewed
Just some additional pointers :)

I also am not 100% convinced we even need the `BedAssignmentView`s - without being able to see the room occupations (see comments above), it is not a good idea to assign beds anyways.

So I'd argue we should only ever assign beds inside the `WardView`.

2023-11-15 09:15 UTC, charludo commented on ycms/cms/forms/bed_assignment/bed_assignment_form.py
> +        return bed_assignment
I don't think this does anything that the default save() method doesn't already do(?)

2023-11-15 09:15 UTC, charludo commented on ycms/cms/views/bed_assignment/bed_assignment_create_view.py
> +        return reverse_lazy("cms:protected:manage_bed_assignment")
This + the UpdateView should just be this view, really. Inherit from TemplateView, and add `get()` and `post()` methods. If get, erturn rendered template+form. If post, check if the `/<pk:int>/`parameter is in the URL.

If it is not, create a new BedAssignment (though as mentioned above - I don't think we ever need to manually add a bed assignment, only implicitly at patient intake).

If it is, retrieve that object and assign it to `form.instance`.

Save form, return redirect to the bed assignments.

It's not that this solution doesn't work, it's just a lot of unnecessary/duplicate code.

2023-11-18 06:37 UTC, charludo commented on ycms/cms/models/timetravel_manager.py
> +request_signal.connect(set_request)
Quick question, are you merging the develop branch into your feature branch, or rebasing your feature branch onto the develop branch? I'm a bit confused why the develop changes always show up in your feature branch, it makes it a bit hard to see what was changed in your PR 😅 

Could zou please rebase this PR onto develop so these changes disappear?

2023-11-19 13:45 UTC, noworneverev commented on ycms/cms/forms/bed_assignment/bed_assignment_form.py
> +        return bed_assignment
I've removed this. I think we can keep the `BedAssignmentViews` just for admin use. It's a bit inconvenient to view and edit bedassignment in the default admin page.

2023-11-19 13:54 UTC, noworneverev commented on ycms/cms/views/bed_assignment/bed_assignment_create_view.py
> +        return reverse_lazy("cms:protected:manage_bed_assignment")
I've removed the createview as it's not necessary.

2023-11-19 13:54 UTC, noworneverev commented
> Also some other "nitpicks":
> 
> * Why not put the assignment information and action in the free space we already have, in the same style?
>   ![image](https://user-images.githubusercontent.com/47758554/283019267-4f5fe4c2-6180-448d-a3d4-a192f7ab5bb0.png)
> * "New Bed Assignment" is not necessary, unless I am missing a usecase?
> * I like the new sidebar! Could you also show the same diagnosis information in the room sidebar?
> * Maybe we could also show insurance type in the assignment sidebar?
> * Don't show discharge date in the assignment. In fact, I think we can also remove discharge date ffrom the room sidebar: Realistically, either you are already discharged (and no longer show up in the room sidebar), or you don't have a discharge date. I know we have the discharge date in the data, but AFAIK that is only because we get the complete dataset all at once, rather than linearly in time.
> 
> I know these are a LOT of change requests, I'm sorry 🙈

I redesign the room's sidepanel and limit that only admission date and discharge date can be modified at this point.

2023-11-19 13:56 UTC, noworneverev commented
> Thank you! I have not had a closer look at the code yet, just tried it out locally, and everything seems to work!
> 
> However, I have some concerns about the workflow, especially the BedAssignmentForm.
> 
> After clicking on "Assign" in the sidebar, the form pops up and we can manually set a bed. But all the other fields are irrelevant to the situation, and it is not intuitive at all what bed we are assigning to, plus we don't know if there is someone of a different gender, or much older/younger, or privately insured in the room.
> 
> Could you rework this so no form is shown at all? The new workflow would be:
> 
> * Click "assign" in the sidebar
> * The sidebar closes, and the user can click on any of the rooms
> * The patient is assigned to the first free bed in the room (e.g. use JS to submit the form in the background)
> * The sidebar reopens
> 
> Additionally, we would need to indicate that we are currently in the "assignment mode":
> 
> * show something like "Assigning patient {{ patient name,... }}" somewhere
> * in place of the "Unassigned Patients: x" + buttons show the patients relevant information (age, gender, diagnosis)
> * visually indicate what rooms they are assignable to: set background and text color of private, other-gender, and large age difference rooms to grey, make full rooms or rooms with one person if the patient is accompanied unselectable.
> * same thing when editing an assignment, but also indicate the current room
> 
> I really like the indications (large age gap, insurance state and so on) but I think they, too, should only be shown during assignment - afterwards, they don't really matter.

I have redesigned the assigning workflow.

2023-11-23 13:49 UTC, charludo requested changes
Some more comments 😅

2023-11-23 13:49 UTC, charludo commented on ycms/cms/forms/bed_assignment/bed_assignment_form.py
> +from ..custom_model_form import CustomModelForm
```suggestion
from django import forms
from django.utils import timezone

from ...models import BedAssignment
from ..custom_model_form import CustomModelForm
```
Took me a while to figure out why pylint was passing despite these imports - you are missing an `__init__.py` in the `bed_assignment` directory!

2023-11-23 13:49 UTC, charludo commented on ycms/cms/forms/bed_assignment/bed_assignment_form.py
> +        self.fields["medical_record"].disabled = True
```suggestion
```
I get what you are trying to do with the disabled field, but I think there's a cleaner way (see next comment)

2023-11-23 13:49 UTC, charludo commented on ycms/cms/forms/bed_assignment/bed_assignment_form.py
> +            "admission_date": forms.NumberInput(
```suggestion
        widgets = {
            "medical_record": forms.HiddenInput(),
            "admission_date": forms.NumberInput(
```
This way the field will not be shown to the user at all.

2023-11-23 13:49 UTC, charludo commented on ycms/cms/forms/bed_assignment/bed_assignment_form.py
> +
```suggestion

    def save(self, commit=True):
        """
        This method extends the default ``save()``-method of the base :class:`~django.forms.ModelForm`
        to create a new bed assignment.

        :param commit: Whether or not the changes should be written to the database
        :type commit: bool

        :return: The saved bed assignment
        :rtype: ~ycms.cms.models.bed_assignment.BedAssignment
        """
        if self.instance:
            self.cleaned_data["medical_record"] = self.instance.medical_record
        return super().save(commit)
```
Disabled/Hidden fields can still be manipulated by the user; this ensures the medical_record of a bed assignment cannot be tampered with.

2023-11-23 13:49 UTC, charludo commented on ycms/cms/models/bed.py
> +        return True
IMO the comments are pretty self-explanatory and we can remove them, but I'm also OK with leaving them. Your choice!

2023-11-23 13:49 UTC, charludo commented on ycms/cms/models/room.py
> +                )
(since this is the same logic, but without comments)

2023-11-23 13:49 UTC, charludo commented on ycms/cms/models/room.py
> +        return [patient.age for patient in self.patients()]
How about this:
```suggestion
        return [patient.age for patient in self.patients()] if self.patients() else [0]
```
so we can then have an easier time with the other properties (see next comments)?

2023-11-23 13:49 UTC, charludo commented on ycms/cms/models/room.py
> +        return None
Then we can do:
```suggestion
        return -max(self.patient_ages)
```

2023-11-23 13:49 UTC, charludo commented on ycms/cms/models/room.py
> +        return None
And also this:
```suggestion
        return max(self.patient_ages) - min(self.patient_ages)
```

2023-11-23 13:49 UTC, charludo commented on ycms/cms/templatetags/custom_filters.py
> +def times(number):
would `range_` not be a more fitting name?
I am not quite sure why we need this anyways (see next comments) 😅

2023-11-23 13:49 UTC, charludo commented on ycms/cms/templates/ward/ward_room_card.html
> +</div> -->
```suggestion
    <!-- For later fancy card use -->
    <!-- <div class="relative">
        {% for _ in room.beds %}
        <i icon-name="bed-single" class="w-16 h-16 text-white"></i>
        {% endfor %}
</div> -->
```

But anyways, since this is not used in this/this PR, I would strongly advocate for removing this. Even if we need it later, currently it's just dead code.

2023-11-23 13:49 UTC, charludo commented on ycms/cms/templates/bed_assignment/assign_room_card.html
> +{% load custom_filters %}
As far as I can tell, this entire file is identical to `ward_room_card.html`. Why do we need it? 😅

2023-11-23 13:49 UTC, charludo commented on ycms/cms/urls/protected.py
> +    ),
```suggestion
```
Isn't this a duplicate of the `discharge_patient` route added in line 17?

2023-11-23 13:49 UTC, charludo commented on ycms/cms/views/bed_assignment/bed_assignment_update_modal_view.py
> +    form_class = BedAssignmentForm
I am really unsure why we need this view, tbh. Correct me if I'm wrong, ut this is only used so that you can use JS to fetch the form for a specific bed assignment, correct?

Wouldn't it be a lot easier / less complicated to just include a form for each patient from the beginning?

Edit: actually, I have another easier idea. I will create a draft of that idea in a separate branch and ping you later. Ignore this for now 😄

2023-11-23 13:49 UTC, charludo commented on ycms/cms/views/bed_assignment/bed_assignment_update_view.py
> +        return kwargs
```suggestion
```

2023-11-23 13:49 UTC, charludo commented on ycms/cms/views/bed_assignment/bed_assignment_update_view.py
> +            )
I cannot think of a better way to do this, but it still seems really hacky. The more I think about it, the more I am certain that we should drop the `/bed-assignments/` view alltogether. It complicates a lot of things (like this) without providing any benefit to the user.

Esp. since there is no way to create a patient or a medical record without a bed assignment, unless you are using the `/admin/`  backend, but you would still need to use the backend for patient+medical_record, at which point, why switch to this for the bed_assignment?

2023-11-23 13:49 UTC, charludo commented on ycms/cms/views/patients/assign_view.py
> +        # bed_assignment = BedAssignment.objects.get(id=assignment_id)
```suggestion
```

2023-11-23 13:49 UTC, charludo commented on ycms/cms/views/patients/assign_view.py
> +        assignment_id = kwargs["assignment_id"]
Haven't tested - but shouldn't this:
```suggestion
        bed_id = request.POST.get("bed_id")
        assignment_id = kwargs["assignment_id"]
```
also work?

2023-11-23 13:49 UTC, charludo commented on ycms/static/src/index.ts
> +    handleButtonEdit();
Could we maybe handle these inside dedicated `load` eventlisteners inside the files? We would save ourselves having to export/import the functions and this eventlistener would not have to handle lots of unrelated tasks.

2023-11-23 14:03 UTC, charludo commented on ycms/cms/templates/patient/patient_card.html
> +        </div>
This is duplicate to `ward_drawer`.html. Please move into own partial temlate, then import in both of those.

2023-11-23 14:06 UTC, charludo commented on ycms/cms/templates/patient/patient_card.html
> +                {% if patient.current_admission_date %}{{ patient.current_admission_date }}{% endif %}
```suggestion
                {{ patient.current_admission_date }}
```
`None` values (or nonexistent attributes, for that matter) will simply not be rendered, ther is no advantage to checking like this.

There are a bunch of these, please change them all, I just picked this by chance 😄

2023-11-23 15:32 UTC, charludo commented
Some more things:

- could you also move the buttons into the unassigned patients card?
- I really likethe new cards inside the ward view sidebar! Could you also use them for the Assignment sidebar?
- could you solve the assignment flow without redirecting to a different (`/patients/assign/`) view? This view is 98% the same as the ward view. Could you instead just check with JS if we are currently assigning, and if so show the patient information at the top and color the rooms etc? (This probably can largely be done in CSS, not a lot of JS required). Then this view and template would not be needed anymore.
- speaking of: you currently show two cards at the top while assigning a ptient. The first one is superfluous IMO. Could you only show the second one, and make it the same height as the normal info cards, so the corridor and rooms don't shift when assigning a patient?

And lastly a general thing: It's obvious that you are putting a lot of work into this project, and that is awesome, thank you!! I think you could save yourself a large chunk of that work though if you started reusing the existing code more. A lot of the files you have included in this PR are almost duplicates of other files (I've mentioned a couple of them in the comments above). Slightly changing them would be way easier, and also keep our code way more maintainable.

2023-11-26 11:21 UTC, noworneverev commented on ycms/cms/templatetags/custom_filters.py
> +def times(number):
I'll remove it.

2023-11-26 11:22 UTC, noworneverev commented on ycms/cms/templates/ward/ward_room_card.html
> +</div> -->
Ok, I'll remove it.

2023-11-26 11:24 UTC, noworneverev commented on ycms/cms/templates/bed_assignment/assign_room_card.html
> +{% load custom_filters %}
I'll remove it.

2023-11-26 13:37 UTC, noworneverev commented on ycms/cms/views/patients/assign_view.py
> +        assignment_id = kwargs["assignment_id"]
No, not work.

2023-11-26 13:57 UTC, noworneverev commented on ycms/static/src/index.ts
> +    handleButtonEdit();
ok

2023-11-26 15:10 UTC, noworneverev commented on ycms/cms/templates/patient/patient_card.html
> +                {% if patient.current_admission_date %}{{ patient.current_admission_date }}{% endif %}
It actually be rendered to string None which then shows on the page, it's not intuitive to see such word. 
![image](https://github.com/charludo/ycms/assets/18380064/3b101d9e-6231-403f-8293-2a0b127456bd)

2023-11-26 15:35 UTC, charludo commented on ycms/cms/templates/patient/patient_card.html
> +                {% if patient.current_admission_date %}{{ patient.current_admission_date }}{% endif %}
That is very strange, same thing renders as empty string for me (and AFAIK it should generally not show None, unless somewhere we are returning the string "None").

I guess leave it for now, I'll try to investigate.

2023-11-26 16:33 UTC, charludo commented on ycms/cms/templates/bed_assignment/assign_room_card.html
> +{% load custom_filters %}
Ah, I see. That makes sense.

Although we could potentially even drop the colors in the normal/non-assign view completely, since staff probably don't need a constant warning "this room has 2 out of 2 patients in it", I think?

2023-11-26 17:02 UTC, charludo commented on ycms/cms/templates/patient/patient_card.html
> +                {% if patient.current_admission_date %}{{ patient.current_admission_date }}{% endif %}
Ahhhhh, I get it now (I think, lol). `current_room`, `current_admission_date` and so on explicitly return None. Apparently, None is rendered as "None" (did not know that!).

On the other hand, things like `current_stay` will render as the empty string when the queryset is empty - I assume there's just some logic for that in the queryset's `__str__`.

I see three options:
- leave as is: works, but is a bit verbose IMO.
- use `{{ patient.current_admission_date|default_if_none="' }}` <- I would prefer this if you prefer to solve this in the template
- change the cached properties to return `""` instead of `None`; I don't think this should cause any troubles, since we are not testing for actual `None`-ness anywhere, only for falsy-ness. I would prefer this option, personally, as it is "set and forget", if we require those values somewhere else in a template it will just work

2023-11-27 11:03 UTC, noworneverev commented on ycms/cms/templates/bed_assignment/assign_room_card.html
> +{% load custom_filters %}
Agree, I'll remove the color.

2023-11-28 08:41 UTC, charludo commented
Two things I just noticed:
- clicking on edit in the ward sidebar right now creates an error 
- same as you mentioned in #65, some way to cancel the assignment/transfer workflows would probably be good. I know you can just go back in the browser, but users probably won't know.

2023-11-29 10:06 UTC, noworneverev commented on ycms/cms/views/bed_assignment/bed_assignment_update_view.py
> +            )
The view will be deleted after merge #65

2023-11-29 10:20 UTC, noworneverev commented
> Some more things:
> 
> * could you also move the buttons into the unassigned patients card?
done
> * I really likethe new cards inside the ward view sidebar! Could you also use them for the Assignment sidebar?
done
> * could you solve the assignment flow without redirecting to a different (`/patients/assign/`) view? This view is 98% the same as the ward view. Could you instead just check with JS if we are currently assigning, and if so show the patient information at the top and color the rooms etc? (This probably can largely be done in CSS, not a lot of JS required). Then this view and template would not be needed anymore.

Regarding the current solution to assign the patient in different view is that it involved some server side checkings to be able to display warnings for selected unassigned patient. It's not easy to fully depend on JS and CSS to deal with it. The current solution also opens possibility to assign the patient to a different ward. I would say after aligning the room cards, it's quite user friendly now, we can still open another issue to address redirecting url.

> * speaking of: you currently show two cards at the top while assigning a ptient. The first one is superfluous IMO. Could you only show the second one, and make it the same height as the normal info cards, so the corridor and rooms don't shift when assigning a patient?
done
> 
> And lastly a general thing: It's obvious that you are putting a lot of work into this project, and that is awesome, thank you!! I think you could save yourself a large chunk of that work though if you started reusing the existing code more. A lot of the files you have included in this PR are almost duplicates of other files (I've mentioned a couple of them in the comments above). Slightly changing them would be way easier, and also keep our code way more maintainable.

2023-11-30 10:21 UTC, charludo commented
> Regarding the current solution to assign the patient in different view is that it involved some server side checkings to be able to display warnings for selected unassigned patient. It's not easy to fully depend on JS and CSS to deal with it. The current solution also opens possibility to assign the patient to a different ward. I would say after aligning the room cards, it's quite user friendly now, we can still open another issue to address redirecting url.

Forgot to comment on this yesterday, but: You are absolutely right, I had not considered this!

2023-11-30 10:29 UTC, charludo approved these changes
🎉 🎉 🎉 🎉 🎉

2023-11-30 10:29 UTC, merged