Adding a Central View
charludo/ycms pull request #61
Opened 2023-11-18 21:06 UTC by SnehaR26

### Short description

Adding the central view where combined data from all wards can be viewed and a new ward can be added

### Proposed changes

added a new view called zentral.py, a template to render it called zentral.html  and made changes to protected.py
Still unsure about where it will land with user-based-views
for testing purposes it can be viewed at http://localhost:8086/zentral/ 
- 
- 

### Side effects

The code doesn't give us the values required , needs some resolution with the render method in zentral.py
- 
- 

### Resolved issues

#18 
Fixes: #

2023-11-18 21:13 UTC, charludo requested changes
Alright, this looks more like it 😄😄🎉

You can probably fix a bunch of the failing CircleCI checks bu running `./tools/code_style.sh`.

2023-11-18 21:13 UTC, charludo commented on ycms/cms/views/zentral.py
> +    def newward(self, request):
```suggestion
    def get(self, request, *args, **kwargs):
```

I haven't had a chance to take a look from my PC yet, but this probably won't work, since Django will expect you to implement a get method

2023-11-19 07:50 UTC, charludo requested changes
I've added a couple of comments and suggestions. With those, the project should run, show your view, and list the wards.

I strongly recommend you install the `pylint`, `black`, `prettier`, `eslint`, and `djlint` plugins for VSCode. They will help with formatting, pointing out error sources, and fix some of the failing CircleCI checks (or rather, prefvent you from causing them to fail 😄)

2023-11-19 07:50 UTC, charludo commented on ycms/cms/views/zentral.py
> +        total_beds_count = wards_count*28
```suggestion
        total_beds_count = total_wards_count*28
```

However, this is not accurate. Rooms can have more than 2 beds, and wards can have more or fewer than 14 rooms. What you are looking for is
```python
total_beds_count = sum(ward.total_beds for ward in Ward.objects.all())
```
which uses the `total_beds` cached property we already implemented on the Ward model.

2023-11-19 07:50 UTC, charludo commented on ycms/cms/views/zentral.py
> +        total_doctors_count = User.objects.filter(job_type__contains='DOCTOR').count()
```suggestion
        total_doctors_count = User.objects.filter(job_type=job_types.DOCTOR).count()
```
(same for the Nurses)

For this to work, you need to
```python
from ..constants import job_types
```

THe point of these constants is so we don't have random hardcoded strings in our code.

2023-11-19 07:50 UTC, charludo commented on ycms/cms/urls/protected.py
>          include(
On line 6 of the `protected.py` you will find
```python
from ..views import authentication, index, patients, ward
```

you need to add your import there:

```python
from ..views import authentication, index, patients, ward, zentral
```

2023-11-19 07:50 UTC, charludo commented on ycms/cms/templates/zentral.html
> +    {% for ward in total_wards %}
```suggestion
    {% for ward in wards %}
```

`total_wards` is what you called your variable in `zentral.py`. However, you assigned that variable to `"wards"` in the context object, so we have to use that here :)

2023-11-26 10:44 UTC, charludo requested changes
Thank you! 🎉 

Please don't be put off by how many comments I've added, most are simple stylistic things 🙈 

Also, please know that you can and should challenge these suggestions if you think they don't make sense - after all, the person who wrote the changes has for more inside into the how and why than the reviewer.

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
Please move this file to either `ycms/cms/views/ward/ward_list_view.py` or `ycms/cms/views/ward/ward_management_view.py`, since this more accurately describes its function.

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +        as well as a form for creating a new one(not implemented yet)
```suggestion
        as well as a form for creating a new one
```

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +        # ward list which acts as a iterable object
```suggestion
```
Comments of this nature don't really add any information

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +        # total number of wards
```suggestion
```
Same here - since you have chosen a good, self describing variable name (`total_wards_count`), since comment does not add new information.

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +        # total number of beds
```suggestion
```

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +        # total occupied beds
```suggestion
```

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +            total_available_beds += ward.available_beds
```suggestion
        total_occupied_beds = sum(ward.occupied_beds for ward in total_wards)
        total_available_beds = sum(ward.available_beds for ward in total_wards)
```
Your version works, of course, this is just a bit more concise / pythonic

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +        # total number of wards
Actually, maybe you could change the `total_` prefix to `all_` (or remove it completely) for most variables? E.g. I think `wards = Ward.objects.all()` makes more semantic sense than `total_wards`.

But this is very, very nitpicky, so decide for yourself if you want to do that work 😅

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +        # total number of doctors
```suggestion
```

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +        # total number of nurses
```suggestion
```

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +        # context = {"wards list":wards_list}
```suggestion
```

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +            return redirect("cms:protected:zentral")
OK, I know we implemented this together, but there is actually a "nicer" way to do this. The issue with this solution is that if an error occurs, we are being *redirected* to the same view, and this deletes all our input fields, even if they did not contain an error.

Instead, you could do it like Yan-Ying did in `ycms/cms/views/ward/ward_view.py`, 
and extract getting all the ward info (`total_wards`, `total_wards_count`, `total_beds_count`, `total_doctors_count`, `total_nurses_count`, `total_available_beds`, `total_occupied_beds`) into a separate helper function, which you then use in botth `get()` and `post()` to return `render(...)` instead of `redirect(...)`.

In both `get()` and `post()` you would then instantiate the `ward_form` just like you currently do. This would then render the form with whatever the user put into the form fields before the error occurred, and they would have a much simpler time fixing their mistake!

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +                "wardform": ward_form,
I did not mention it during our coworking session, sorry - but generally we would want to keep consisting naming standards, e.g. `wards_count` instead of `wardscount` etc.

It's not super important, so you don't have to change these if you don't feel like it, but I thought I would still mention it as a heads up for future PRs 😄

2023-11-26 10:44 UTC, charludo commented on ycms/locale/de/LC_MESSAGES/django.po
> +msgstr "Gesamtzahl der Stations"
```suggestion
msgstr "Gesamtzahl der Stationen"
```

2023-11-26 10:44 UTC, charludo commented on ycms/locale/de/LC_MESSAGES/django.po
> +msgstr "Gesamtzahl der Verfügbare Betten"
```suggestion
msgstr "Gesamtzahl der verfügbaren Betten"
```

2023-11-26 10:44 UTC, charludo commented on ycms/locale/de/LC_MESSAGES/django.po
> +msgstr "Gesamtzahl der Belegte Betten"
```suggestion
msgstr "Gesamtzahl der belegten Betten"
```

2023-11-26 10:44 UTC, charludo commented on ycms/locale/de/LC_MESSAGES/django.po
> +msgstr "Gesamtzahl der Krankenschwestern"
```suggestion
msgstr "Gesamtzahl der Krankenpflegenden"
```
Gender neutral / Krankenschwestern ist a bit outdated

2023-11-26 10:44 UTC, charludo commented on ycms/locale/de/LC_MESSAGES/django.po
> +msgstr "Station Angaben"
```suggestion
msgstr "Stationsdetails"
```

2023-11-26 10:44 UTC, charludo commented on ycms/locale/de/LC_MESSAGES/django.po
> +msgstr "Eine Neue Station Hinzufügen"
```suggestion
msgstr "Neue Station Hinzufügen"
```
If you are differentiating between "Add a new ward" and "Add new ward" in English, I think we should do the same in German.

2023-11-26 10:44 UTC, charludo commented on ycms/locale/de/LC_MESSAGES/django.po
> +msgstr "Station Angaben"
```suggestion
msgstr "Stationsdetail"
```

2023-11-26 10:44 UTC, charludo commented on ycms/locale/de/LC_MESSAGES/django.po
> +msgstr "Hinzufügung einer neuen Station \"{}\" erfolgreich"
```suggestion
msgid "Addition of new ward \"{}\" successful!"
msgstr "Hinzufügung der neuen Station \"{}\" erfolgreich!"
```

2023-11-26 10:44 UTC, charludo commented on ycms/cms/views/zentral.py
> +            request, _('Addition of new ward "{}" successful!.').format(ward.name)
```suggestion
            request, _('Addition of new ward "{}" successful!').format(ward.name)
```
(THen you will also have to do this, otherwise the translation will not recognize the changed string)

2023-11-26 10:44 UTC, charludo commented on ycms/cms/urls/protected.py
> +    path("zentral/", zentral.ZentralView.as_view(), name="zentral"),
```suggestion
    path("ward/list/", zentral.ZentralView.as_view(), name="ward_list"),
```
Another option would be `ward/manage/` as a route and `ward_management` as a name. In both cases, please move this line to the bottom of the file, newar the other `ward/` routes.

THe reason I would suggest renaming and moving this endpoint is that ZBM/zentral are not really functions, ZBM is just a user role we have, and generally speaking it makes more sense to name views and routes based on their functionality, not who will be able to use the functionality.

2023-11-26 10:44 UTC, charludo commented on ycms/cms/templates/zentral.html
> +        </div>
Quite a bit of this is redundant to the list view at the bottom of the page, esp. the list of wards. I would suggest the following:
- rearrange "Total Wards", "Total Doctors", "Total Nurses" so they are all in the top row of information, since they are more "highlevel" information". 
- put "Total Beds", "Available Beds", "Occupied Beds" in the second row, since those three are related.
- remove the list of wards displayed here

2023-11-26 10:44 UTC, charludo commented on ycms/cms/templates/zentral.html
> +            </form>
```suggestion
            <form enctype="multipart/form-data"
                  method="post"
                  id="ward_form"
                  class="mb-12 flex justify-between items-center"
                  data-unsaved-warning>
                {% csrf_token %}
                {% for field in wardform %}
                    <div>
                        <label for="{{ field.id_for_label }}"
                               {% if field.field.required %}class="field-required"{% endif %}>{{ field.label }}</label>
                        {% render_field field %}
                        <div class="help-text">{{ field.help_text }}</div>
                    </div>
                {% endfor %}
                <button type="submit" class="btn mt-4">{% translate "Add New Ward" %}</button>
            </form>
```

I know this is more verbose, but IMO looks way nicer since this is a small form:
![image](https://github.com/charludo/ycms/assets/47758554/0099fcd1-4ee1-4157-823e-f589cab78b41)

2023-11-26 10:44 UTC, charludo commented on ycms/cms/templates/zentral.html
> +            <div class="mb-4 text-2xl font-semibold">{% translate "Wards Detail" %}</div>
```suggestion
            <div class="mb-4 text-2xl font-semibold">{% translate "All Wards" %}</div>
```
Super pendantic, and feel free to ignore. At least to me (and I may be wrong) "Wards Detail" reads more like "a details about all the wards" than "details about each ward".

2023-11-26 10:44 UTC, charludo commented on ycms/cms/templates/zentral.html
> +{% block content %}
```suggestion
{% extends "_base.html" %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}
{% block title %}
    {% translate "Ward Management" %}
{% endblock title %}
{% block content %}
```
THis just makes the browser tab title complete, instead of just reading "Ycms | ".

2023-11-26 10:44 UTC, charludo commented on ycms/cms/templates/zentral.html
Same as with the view file, please move this to either `ycms/cms/templates/ward/ward_list.html` or `ycms/cms/templates/ward/ward_management.html`.

2023-11-26 10:44 UTC, charludo commented on ycms/cms/templates/_base.html
Something has gone wrong here - your PR reverts the changes Yan-Ying made in #63.

Please run the following commands to fix this:
```
git checkout develop
git pull
git checkout central-view
git restore --source develop -- ycms/cms/templates/_base.html
```

2023-11-26 10:44 UTC, charludo commented on ycms/cms/templates/_base.html
> +                    {% url 'cms:protected:zentral' as url %}
```suggestion
                    {% url 'cms:protected:ward_list' as url %}
```
(or `ward_management`, depending on your earlier choices) - only do this after restoring the `develop` version of this file!

2023-11-26 10:44 UTC, charludo commented on ycms/cms/templates/_base.html
> +                        <i icon-name="activity"></i> {% translate "ZBM View" %}
```suggestion
                        <i icon-name="activity"></i> {% translate "Ward List" %}
```
(or `Ward Management`, depending on your earlier choices) - only do this after restoring the `develop` version of this file!

2023-11-28 22:49 UTC, SnehaR26 commented
@charludo Thank you so much for such a comprehensive review🤗. Yes it makes sense to add it under ward/ so I have changed it to ward/ward_management for both .py and .HTML. I have made the rest of additions, deletions as well.  Currently check_translations is failing and i am figuring that out. I have checked for all empty strings and fuzzy logic. Does that file take the develop branch version into account while checking. I did run git pull for develop branch before making changes. Adding the output below:

`Checking if YCMS is installed...
✔ YCMS is installed
Checking translation file for problems...
❌ Your translation file is not up to date! 💣
Please add the current changes to your commit:

┌──────────────────────────────────────
│ diff --git a/ycms/locale/de/LC_MESSAGES/django.po b/ycms/locale/de/LC_MESSAGES/django.po
│ index 2a080e6..f000ea8 100644
│ --- a/ycms/locale/de/LC_MESSAGES/django.po
│ +++ b/ycms/locale/de/LC_MESSAGES/django.po
│ @@ -392,9 +392,9 @@ msgstr " Logo"
│  msgid "General"
│  msgstr "Allgemein"
│
│ -#: cms/templates/_base.html
│ -msgid "ZBM View"
│ -msgstr "ZBM Ansicht"
│ +#: cms/templates/_base.html cms/templates/ward/ward_management.html
│ +msgid "Ward Management"
│ +msgstr "Stationsverwaltung"
│
│  #: cms/templates/_base.html cms/templates/patients_list.html
│  msgid "Manage Patients"
│ @@ -647,66 +647,62 @@ msgstr "Bettenverfügbarkeit"
│  msgid "Available Beds"
│  msgstr "Verfügbare Betten"
│
│ -#: cms/templates/ward/ward_info.html cms/templates/zentral.html
│ +#: cms/templates/ward/ward_info.html cms/templates/ward/ward_management.html
│  msgid "Total Beds"
│  msgstr "Gesamtzahl der Betten"
│
│ -#: cms/templates/ward/ward_modal.html
│ -msgid "Close modal"
│ -msgstr "Modal schließen"
│ -
│ -#: cms/templates/ward/ward_modal.html
│ -msgid "Are you sure you want to discharge this patient?"
│ -msgstr "Sind Sie sicher, dass Sie diesen Patienten entlassen möchten?"
│ -
│ -#: cms/templates/ward/ward_modal.html
│ -msgid "Yes"
│ -msgstr "Ja"
│ -
│ -#: cms/templates/ward/ward_modal.html
│ -msgid "No"
│ -msgstr "Nein"
│ -
│ -#: cms/templates/zentral.html
│ +#: cms/templates/ward/ward_management.html
│  msgid "YCMS at a glance"
│  msgstr "YCMS im Überblick"
│
│ -#: cms/templates/zentral.html
│ +#: cms/templates/ward/ward_management.html
│  msgid "Total Wards"
│  msgstr "Gesamtzahl der Stationen"
│
│ -#: cms/templates/zentral.html
│ -msgid "Total Available Beds"
│ -msgstr "Gesamtzahl der verfügbaren Betten"
│ -
│ -#: cms/templates/zentral.html
│ +#: cms/templates/ward/ward_management.html
│  msgid "Total Doctors"
│  msgstr "Gesamtzahl der Ärzte"
│
│ -#: cms/templates/zentral.html
│ -msgid "Total Occupied Beds"
│ -msgstr "Gesamtzahl der belegten Betten"
│ -
│ -#: cms/templates/zentral.html
│ +#: cms/templates/ward/ward_management.html
│  msgid "Total Nurses"
│  msgstr "Gesamtzahl der Krankenpflegenden"
│
│ -#: cms/templates/zentral.html
│ -msgid "Ward Details"
│ -msgstr "Stationsdetails"
│ +#: cms/templates/ward/ward_management.html
│ +msgid "Total Available Beds"
│ +msgstr "Gesamtzahl der verfügbaren Betten"
│ +
│ +#: cms/templates/ward/ward_management.html
│ +msgid "Total Occupied Beds"
│ +msgstr "Gesamtzahl der belegten Betten"
│
│ -#: cms/templates/zentral.html
│ +#: cms/templates/ward/ward_management.html
│  msgid "Add a New Ward"
│  msgstr "Neue Station Hinzufügen"
│
│ -#: cms/templates/zentral.html
│ +#: cms/templates/ward/ward_management.html
│  msgid "Add New Ward"
│  msgstr "Eine Neue Station Hinzufügen"
│
│ -#: cms/templates/zentral.html
│ +#: cms/templates/ward/ward_management.html
│  msgid "Details about Wards"
│  msgstr "Details über Stationen"
│
│ +#: cms/templates/ward/ward_modal.html
│ +msgid "Close modal"
│ +msgstr "Modal schließen"
│ +
│ +#: cms/templates/ward/ward_modal.html
│ +msgid "Are you sure you want to discharge this patient?"
│ +msgstr "Sind Sie sicher, dass Sie diesen Patienten entlassen möchten?"
│ +
│ +#: cms/templates/ward/ward_modal.html
│ +msgid "Yes"
│ +msgstr "Ja"
│ +
│ +#: cms/templates/ward/ward_modal.html
│ +msgid "No"
│ +msgstr "Nein"
│ +
│  #: cms/utils/email_utils.py
│  msgid "YCMS | Activate your account"
│  msgstr "YCMS | Aktivieren Sie Ihren Account"
│ @@ -776,7 +772,7 @@ msgstr "Patient*in \"{} {}\" wurde gespeichert."
│  msgid "Intake for patient \"{} {}\" with diagnosis \"{}\" has been saved."
│  msgstr "Patient*in \"{} {}\" mit Diagnose \"{}\" wurde gespeichert."
│
│ -#: cms/views/zentral.py
│ +#: cms/views/ward/ward_management_view.py
│  msgid "Addition of new ward \"{}\" successful!"
│  msgstr "Hinzufügung der neuen Station \"{}\" erfolgreich!"
│
│ @@ -792,6 +788,8 @@ msgstr "Deutsch"
│  msgid "English"
│  msgstr "Englisch"
│
│ +#~ msgid "Ward Details"
│ +#~ msgstr "Stationsdetails"
│
│  #~ msgid "Home"
│  #~ msgstr "Start"
└──────────────────────────────────────`

2023-11-29 07:27 UTC, charludo commented
> @charludo Thank you so much for such a comprehensive review🤗. Yes it makes sense to add it under ward/ so I have changed it to ward/ward_management for both .py and .HTML. I have made the rest of additions, deletions as well.

Thanks! I will have another look!

Just one thing for the future: to the bottom right of the suggestions, there is a "commit suggestion" button. Feel free to use it - then you won't have to manually implement the changes. This will also "resolve" the conversation, marking it as "done" for both you and the reviewer. 

As it is right now, all the conversations are still "unresolved" - could you please go through them again, make sure you've implemented the changes, then mark the conversation as "resolved"?

2023-11-29 08:01 UTC, charludo requested changes
Thank you! This is almost ready to merge, I just have some more stylistic comments.

Feel free to use "commit suggestion" on them 😄

2023-11-29 08:01 UTC, charludo commented on ycms/cms/templates/ward/ward_management.html
> +                        <label for="{{ field.id_for_label }}"
```suggestion
                  class="mb-12 flex justify-between items-center gap-4"
                  data-unsaved-warning>
                {% csrf_token %}
                {% for field in ward_form %}
                    <div class="grow">
                        <label for="{{ field.id_for_label }}"
```
Sorry, I missed this when looking at it on a smaller screen

2023-11-29 08:01 UTC, charludo commented on ycms/cms/views/ward/ward_management_view.py
> +        return ward_info
```suggestion
    @staticmethod
    def _get_ward_info():
        wards = Ward.objects.all()
        return {
            "wards": wards,
            "wards_count": wards.count(),
            "beds_count": sum(ward.total_beds for ward in wards)
            "occupied_beds": sum(ward.occupied_beds for ward in wards),
            "available_beds": sum(ward.available_beds for ward in wards),
            "doctors_count": User.objects.filter(job_type=job_types.DOCTOR).count(),
            "nurses_count": User.objects.filter(job_type=job_types.NURSE).count(),
        }
```
This does the exact same thing (apart from the fix to `beds_count` that I have mentioned before), but is a bit more pythonic and nicer to read / add stuff later. I've also taken the liberty to remove the `all_` prefixes, since they are all in one place now :)

2023-11-29 08:01 UTC, charludo commented on ycms/cms/views/ward/ward_management_view.py
> +        )
```suggestion
        return render(
            request,
            self.template_name,
            {
                "ward_form": ward_form,
                **self._get_ward_info(),
                **super().get_context_data(**kwargs),
            },
        )
```
This will "unpack" the dictionary you get from `self._get_ward_info` - the resulting dict that will be returned contains all the same `"key": value` pairs as the function returns.

I would also move the fetching of the wards objects to that new method.

Also please keep the `super().get_context_data`, depending on our request handling / routing / the base class the view is inheriting from, this actually does a lot.

2023-11-29 08:01 UTC, charludo commented on ycms/cms/views/ward/ward_management_view.py
> +            return redirect("cms:protected:ward_management")
Ah, this is what I meant in the previous review. Since you implemented the separate info method, we can now simply do this:
```suggestion
            return render(
                request,
                self.template_name,
                {
                    "ward_form": ward_form,
                    **self._get_ward_info(),
                    **super().get_context_data(**kwargs),
                },
            )
```
This is the same as in `get()`, but since you have instantiated the Ward form with the data the user entered, it will also be displayed with the data they entered!

2023-11-29 08:01 UTC, charludo commented on ycms/cms/views/ward/ward_management_view.py
> +        all_wards = Ward.objects.all()
```suggestion
```
Cleanup, since now no longer needed

2023-11-29 08:01 UTC, charludo commented on ycms/cms/views/ward/ward_management_view.py
> +
```suggestion

        :return: List of all wards
        :rtype: ~django.template.response.TemplateResponse
```
Not sure where that went! 😄

2023-11-29 08:01 UTC, charludo commented on ycms/locale/de/LC_MESSAGES/django.po
> +msgstr "Eine Neue Station Hinzufügen"
This one is still unresolved, for example

2023-11-29 08:01 UTC, charludo commented on ycms/cms/urls/protected.py
> +from ..views.ward import ward_management_view
```suggestion
```
We are already implementing the all the ward views as `ward` above.
Instead, please add `from .ward_management_view import WardManagementView` in `ycms/cms/views/ward/__init__.py`

2023-11-29 08:01 UTC, charludo commented on ycms/cms/urls/protected.py
> +        ward_management_view.ZentralView.as_view(),
```suggestion
        ward.WardManagementView.as_view(),
```

2023-11-29 08:01 UTC, charludo commented on ycms/cms/views/ward/ward_management_view.py
> +class ZentralView(TemplateView):
```suggestion
class WardManagementView(TemplateView):
```

2023-11-29 08:01 UTC, charludo commented on ycms/cms/templates/ward/ward_management.html
> +    </div>
Due to the changes to `_get_ward_info`, this simplifies:
```suggestion
    <div class="col-span-1 sm:col-span-2 md:col-span-2 lg:col-span-2 xl:col-span-2">
        <div class="rounded-lg border border-gray-300 bg-white p-4 shadow-md flex flex-col h-full">
            <div class="mb-4 text-2xl font-semibold">{% translate "YCMS at a glance" %}</div>
            <div class="grid grid-cols-3">
                <div>
                    <div class="text-lg font-semibold">{% translate "Total Wards" %}</div>
                    <div class="text-3xl font-bold">{{ wards_count }}</div>
                </div>
                <div>
                    <div class="text-lg font-semibold">{% translate "Total Doctors" %}</div>
                    <div class="text-3xl font-bold">{{ doctors_count }}</div>
                </div>
                <div>
                    <div class="text-lg font-semibold">{% translate "Total Nurses" %}</div>
                    <div class="text-3xl font-bold">{{ nurses_count }}</div>
                </div>
                <div>
                    <div class="text-lg font-semibold">{% translate "Total Beds" %}</div>
                    <div class="text-3xl font-bold">{{ beds_count }}</div>
                </div>
                <div>
                    <div class="text-lg font-semibold">{% translate "Total Available Beds" %}</div>
                    <div class="text-3xl font-bold">{{ available_beds }}</div>
                </div>
                <div>
                    <div class="text-lg font-semibold">{% translate "Total Occupied Beds" %}</div>
                    <div class="text-3xl font-bold">{{ occupied_beds }}</div>
                </div>
            </div>
        </div>
    </div>
```

2023-11-29 08:01 UTC, charludo commented on ycms/cms/templates/ward/ward_management.html
> +                {% for ward in all_wards %}
```suggestion
                {% for ward in wards %}
```

2023-11-30 11:02 UTC, charludo requested changes
Almost done!
- one suggestion (see below)
- afterwards you will have to run translate and check_translations again
- then please squash all commits again

and then this is also ready to merge :)

2023-11-30 11:02 UTC, charludo commented on ycms/cms/templates/ward/ward_management.html
> +                    <th align="left">Available</th>
```suggestion
                    <th align="left">{% translate "Ward Number" %}</th>
                    <th align="left">{% translate "Ward Name"  %}</th>
                    <th align="left">{% translate "Number of Beds"  %}</th>
                    <th align="left">{% translate "Available"  %}</th>
                    <th align="left">{% translate "Occupied"  %}</th>
```
Missing translations, and also I just noticed the order of available/occupied was reversed compared to the table rows ^^

2023-11-30 21:16 UTC, charludo approved these changes
🎉🎉🎉

2023-12-01 12:04 UTC, merged