add responsive menu
charludo/ycms pull request #64
Opened 2023-11-19 23:56 UTC by noworneverev

### Short description
Add responsive menu

### Proposed changes
Automatically minimize the the menu in small screen
- 
- 

### Side effects

- 
- 

### Resolved issues

Fixes: #63

2023-11-20 05:57 UTC, charludo requested changes
Thanks, this is a very good idea, and I'm impressed how good the site (esp. the ward view 😄) looks on mobile with this!

I have two thoughts:
- as mentioned in the comments below, there's no need for a second, mobile menu, since it just copies the structures from the desktop menu. Please just apply the classes/animations to the `sidebar`.
- Could you maybe also swap out the icon of the menu on click? Just would be a nice touch I think :D E.g. from icon name `menu` to `x` or something like that.

2023-11-20 05:57 UTC, charludo commented on ycms/static/src/js/utils/menu.ts
> +        mobileMenu?.classList.toggle("hidden");
`hidden` cannot be animated, sadly. How about `-translate-x-full`?

2023-11-20 05:57 UTC, charludo commented on ycms/static/src/css/style.scss
> +    transition: all 0.3s ease;
I think you want to apply the transition duration to the mobile/menu sidebar itself, right?

2023-11-20 05:57 UTC, charludo commented on ycms/cms/templates/_hamburger.html
> +<!-- Hamburger menu for smaller screens -->
I appreciate the effort. However, there is really no need for a second menu. You can just apply the classes/styles/animations... to the existing sidebar, so we don't have duplicate structures.

2023-11-20 05:57 UTC, charludo commented on ycms/cms/templates/_base.html
> +             class="fixed h-full w-64 bg-white border-r shadow-md hidden lg:block">
```suggestion
             class="fixed h-full w-64 bg-white border-r shadow-md transform -translate-x-full lg:translate-x-0">
```
This way we can use the one sidebar on desktop and mobile, plus `translate-x` is animateable! :D

2023-11-21 05:49 UTC, charludo approved these changes
Very cool, thank you!

Only nitpick I have is it would be cool if the menu was still full height and the button would move to the right with it, but this absolutely works. SO if you have an idea for that feel free to implement it, otherwise go ahead and merge 😄

2023-11-21 09:02 UTC, noworneverev commented
> Very cool, thank you!
> 
> Only nitpick I have is it would be cool if the menu was still full height and the button would move to the right with it, but this absolutely works. SO if you have an idea for that feel free to implement it, otherwise go ahead and merge 😄

I think it's enough for now, we can improve it later.

2023-11-21 09:03 UTC, merged