add fancy room cards
charludo/ycms pull request #78
Opened 2023-11-30 23:23 UTC by noworneverev

### Short description
Add fancy room cards

### Proposed changes

- 
- 

### Side effects

- 
- 

### Resolved issues

Fixes: #45

2023-12-01 08:04 UTC, charludo requested changes
Very cool!!! 🎉 

Looks really great!

One small coment, plus could you maybe include this new information (+ the reamining duration) to the patient detail card? Either standalone, or maybe even like:

**Admission date:**  Dec. 26, 2023  (in 25 days)
**Discharge date:** Jan. 26, 2024 (in 56 days)

or, if current stay

**Admission date:**  Nov. 26, 2023  (5 days ago)
**Discharge date:** Jan. 26, 2024 (in 56 days)

Btw, I think you could handle all that logic ("day" or "days", "in" or "ago",...) inside the cached property, that's probably easier, just from a coding standpoint :D

2023-12-01 08:04 UTC, charludo commented on ycms/cms/models/patient.py
> +        :rtype: ~ycms.cms.models.bed_assignment.BedAssignment
Ohhhhh it took me way too long to get that this returns the days the patient has already BEEN in the hospital, not the ones they are going to be.

I think this property is useful esp. in patient details card, but I'm unsure if hospital staff wouldn't be more interested in the "opposite", i.e. how many more days the bed will be occupied? I would suggest using that information on the room cards tbh

2023-12-03 08:37 UTC, noworneverev commented on ycms/cms/models/patient.py
> +        :rtype: ~ycms.cms.models.bed_assignment.BedAssignment
I added a progress bar to show how the patient is doing and put in some labels to make it clear when they're getting discharged and how long they've been here. It might come in handy for some cases. But if there's no discharge date for a patient, it'll just show how long they've been staying.

2023-12-04 12:43 UTC, charludo requested changes
Wow, this looks fantastic!! 🎉 

I have a couple small suggestions (see below), and three other things:
- when assigning someone and there is a room where there is a conflict (mixed gender, age,...) and the current patient in that room is female, that room card is unreadable (or at least looks like it), because the "female" color and the "warning about something" color are the same (e.g. take a look at: http://localhost:8086/patients/assign/1/194/). I would suggest to:
    - change the "female" color to `violet`, since using the same color for women and error is a bit confusing ^^',
    - and to maybe only indicate if a room is compatible/incompatible with a green/red border instead of background color. I think it would convey the same thing, but everything will stay readable.
- the translation for "Transfer" should be "Verschieben" statt "Überweisen". Sorry, did not catch that earlier.
- I think the new properties should be implemented on the `BedAssignment` model instead of the `Patient`. That way we can use them for planned/past stays as well. I think you can just move the code there, and in the template use e.g. `patient.current_stay.duration` instead of `patient.current_stay_duration`

2023-12-04 12:43 UTC, charludo commented on ycms/cms/templates/ward/ward_beds.html
> +            <div class="flex flex-col gap-1 w-full sm:w-full md:w-full lg:w-1/2 xl:w-1/2 min-w-[50%]">
```suggestion
            <div class="flex flex-col gap-1">
                <div class=" flex flex-col items-center">
                    <i icon-name="bed-single"
                       class="w-10 h-10 rounded-lg bg-blue-100 text-blue-800"></i>
                </div>
                {% if patient.current_stay.discharge_date %}
                    <div class="flex justify-end">
                        <span class="text-sm font-medium text-blue-700 dark:text-white">{{ patient.current_stay_progress }}%</span>
                    </div>
                    <div class="w-full bg-gray-200 rounded-full dark:bg-gray-700">
                        <div class="progress-bar bg-blue-600 h-2.5 rounded-full"
                             data-progress="{{ patient.current_stay_progress }}"></div>
                    </div>
                    <span class="bg-gray-100 text-gray-800 text-xs font-medium px-2.5 py-0.5 rounded dark:bg-gray-700 dark:text-gray-300">
                        {% translate "Discharge" %}: {{ patient.current_stay_until_discharge }}
                    </span>
                {% endif %}
                <span class="bg-gray-100 text-gray-800 text-xs font-medium px-2.5 py-0.5 rounded dark:bg-gray-700 dark:text-gray-300">
                    {% translate "Stay" %}: {{ patient.current_stay_duration }}
                </span>
            </div>
        {% else %}
            <div class="flex flex-col gap-1">
```
As far as I can tell this currently makes no difference; on the other hand, when more than 2 patients are in a room, this would overflow, right?

2023-12-04 12:43 UTC, charludo commented on ycms/locale/de/LC_MESSAGES/django.po
> +msgstr "Bleiben"
```suggestion
msgstr "Aufenthalt"
```

2023-12-04 12:43 UTC, charludo commented on ycms/locale/de/LC_MESSAGES/django.po
>  msgstr "Entladung"
```suggestion
msgstr "Entlassen"
```
(did not notice this in previous PR, sry)

2023-12-04 12:43 UTC, charludo commented on ycms/cms/models/patient.py
> +        Helper function to get the date status of a given date
```suggestion
    @staticmethod
    def _get_date_status(date_to_check):
        """
        Helper function to get the date status of a given date
```
since this is not dependent on any object attributes/methods

2023-12-04 21:43 UTC, noworneverev commented on ycms/cms/templates/ward/ward_beds.html
> +            <div class="flex flex-col gap-1 w-full sm:w-full md:w-full lg:w-1/2 xl:w-1/2 min-w-[50%]">
I fix it with grid layout, and now it will not overflow when more than 2 beds in a room.
![image](https://github.com/charludo/ycms/assets/18380064/4ad96dce-49f4-4858-80aa-21cbecccc551)

2023-12-04 21:53 UTC, noworneverev commented
> Wow, this looks fantastic!! 🎉
> 
> I have a couple small suggestions (see below), and three other things:
> 
> * when assigning someone and there is a room where there is a conflict (mixed gender, age,...) and the current patient in that room is female, that room card is unreadable (or at least looks like it), because the "female" color and the "warning about something" color are the same (e.g. take a look at: http://localhost:8086/patients/assign/1/194/). I would suggest to:
>   
>   * change the "female" color to `violet`, since using the same color for women and error is a bit confusing ^^',
>   * and to maybe only indicate if a room is compatible/incompatible with a green/red border instead of background color. I think it would convey the same thing, but everything will stay readable.

I tried using violet, but due to my color blindness, I cannot distinguish between the male's blue and the female's violet 😂. I also attempted to use borders to indicate warnings, but I discovered that it's challenging for color-blind individuals to differentiate between the thin green and red borders. I decided to change the background of warning cards to yellow; I find it more readable now, I think.

> * the translation for "Transfer" should be "Verschieben" statt "Überweisen". Sorry, did not catch that earlier.

Thank you for correction, I basically use translator to do the translation.😅

> * I think the new properties should be implemented on the `BedAssignment` model instead of the `Patient`. That way we can use them for planned/past stays as well. I think you can just move the code there, and in the template use e.g. `patient.current_stay.duration` instead of `patient.current_stay_duration`

Ok, I've moved it to `bed_assignment`

2023-12-05 08:31 UTC, charludo commented
> I tried using violet, but due to my color blindness, I cannot distinguish between the male's blue and the female's violet 😂. I also attempted to use borders to indicate warnings, but I discovered that it's challenging for color-blind individuals to differentiate between the thin green and red borders. I decided to change the background of warning cards to yellow; I find it more readable now, I think.

Oh, alright! Btw, feel free to go into ` tailwind.config.js` and change the colors to something more suitable if you think it helps with accessibility!

And agree, looks good with yellow.

> Thank you for correction, I basically use translator to do the translation.😅

No worries, lol. can always happen with translations, and it slipped by me in a previous review 🤷🏼‍♀️

2023-12-05 08:38 UTC, charludo requested changes
Awesome, almost done!! 🎉 

I think you rebased on `develop`, right? Since the admission/discharge dates now are datetimes, django threw an error because apparently, datetime and date can't be added/subtracted 🤦🏼‍♀️ 

The four suggestions below should fix this.

Commit them, run ` code_style.sh` again, squash the commits - and then it' s ready for merge :)

2023-12-05 08:38 UTC, charludo commented on ycms/cms/models/bed_assignment.py
> +            ((self.discharge_date - current_or_travelled_time().date()).days)
```suggestion
            ((self.discharge_date.date() - current_or_travelled_time().date()).days)
```

2023-12-05 08:38 UTC, charludo commented on ycms/cms/models/bed_assignment.py
> +        duration = int((current_or_travelled_time().date() - self.admission_date).days)
```suggestion
        duration = int((current_or_travelled_time().date() - self.admission_date.date()).days)
```

2023-12-05 08:38 UTC, charludo commented on ycms/cms/models/bed_assignment.py
> +        duration = int((current_or_travelled_time().date() - self.admission_date).days)
```suggestion
        duration = int((current_or_travelled_time().date() - self.admission_date.date()).days)
```

2023-12-05 08:38 UTC, charludo commented on ycms/cms/models/patient.py
> +            days_since := (current_or_travelled_time().date() - date_to_check).days
```suggestion
            days_since := (current_or_travelled_time().date() - date_to_check.date()).days
```

2023-12-05 09:18 UTC, charludo approved these changes
🎉

2023-12-05 09:19 UTC, merged